services:
  gasmetrics:
    build: .
    container_name: gasmetrics
    environment:
      - TZ=Europe/Berlin
    secrets:
      - telegram_token
    restart: unless-stopped
    networks:
      - hauslab

secrets:
  telegram_token:
    file: secrets/telegram_token.txt

networks:
  hauslab:
    external: true
