services:
  gasmetrics:
    build: .
    container_name: gasmetrics
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=s-gas
      - POSTGRES_DB=gasmetrics
    secrets:
      - telegram_token
      - postgres_password
    restart: unless-stopped
    networks:
      - hauslab

secrets:
  telegram_token:
    file: secrets/telegram_token.txt
  postgres_password:
    file: secrets/postgres_password.txt

networks:
  hauslab:
    external: true
