services:
  gasmetrics-server:
    image: sgasparini/gasmetrics-server:latest
    container_name: gasmetrics-server
    environment:
      - PORT=1024
      - TZ=Europe/Berlin
      - POSTGRES_USER=s-gas
      - POSTGRES_DB=gasmetrics
    secrets:
      - postgres_password
    restart: unless-stopped
    networks:
      - hauslab
  gasmetrics-bot:
    image: sgasparini/gasmetrics-bot:latest
    container_name: gasmetrics-bot
    environment:
      - PORT=1024
      - TZ=Europe/Berlin
    secrets:
      - telegram_token 
    networks:
      - hauslab

secrets:
  telegram_token:
    file: gasmetrics-bot/secrets/telegram_token.txt
  postgres_password:
    file: gasmetrics-server/secrets/postgres_password.txt

networks:
  hauslab:
    external: true
