services:
  adguardhome:
    image: adguard/adguardhome:v0.107.74
    ports:
      - 53:53/tcp # DNS
      - 53:53/udp # DNS
      - 1025:80/tcp # web interface
      - 1026:3000/tcp # initial setup
    volumes:
      - config:/opt/adguardhome/conf
      - work:/opt/adguardhome/work

volumes:
  config:
  work:
