services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    ports:
      - 53:53/tcp # DNS
      - 53:53/udp # DNS
    volumes:
      - config:/opt/adguardhome/conf
      - work:/opt/adguardhome/work
    networks:
      - hauslab

volumes:
  config:
  work:

networks:
  hauslab:
    external: true
