name: sysmetrics

services:
  sysmetrics:
    image: sgasparini/sysmetrics:latest
    container_name: sysmetrics
    volumes:
      - /proc:/proc
    environment:
      - TZ=Europe/Berlin
    networks:
      - hauslab
    restart: unless-stopped

networks:
  hauslab:
    external: true
