name: sysmetrics

services:
  sysmetrics:
    build: .
    container_name: sysmetrics
    volumes:
      - /proc:/proc
    environment:
      - TZ=Europe/Berlin
    networks:
      - monitor
      - sysmetrics-observability
    restart: unless-stopped

networks:
  monitor:
    external: true
  sysmetrics-observability:
    external: true
