name: observability

services:
  prometheus:
    image: prom/prometheus:v3.11.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitor
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:12.4
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor
    secrets:
      - grafana_password
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}

secrets:
  grafana_password:
    file: secrets/grafana_password.txt

networks:
  monitor:
    external: true
