services:
  tailscale:
    image: tailscale/tailscale:v1.102
    container_name: tailscale
    hostname: hauslab
    environment:
      - TS_AUTHKEY=/run/secrets/ts_authkey
      - TS_STATE_DIR=/var/lib/tailscale
    secrets:
      - ts_authkey
    volumes:
      - ./tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - net_raw
    networks:
      - hauslab
    restart: unless-stopped

secrets:
  ts_authkey:
    file: ./ts-authkey.txt

networks:
  hauslab:
    external: true
