services:
  svcmonitor:
    build: .
    volumes:
      - ./svcmonitor.log:/usr/src/app/svcmonitor.log
    environment:
      - TZ=Europe/Berlin
    networks:
      - monitor
    restart: unless-stopped

networks:
  monitor:
    external: true
