name: svcmonitor

services:
  svcmonitor:
    build: .
    environment:
      - TZ=Europe/Berlin
    networks:
      - monitor
      - svcmonitor-observability
    restart: unless-stopped

networks:
  monitor:
    external: true
  svcmonitor-observability:
    external: true
