services:
  adguard:
    port: 80
    url: "http://adguard:80"
  nginx:
    port: 80
    url: "http://nginx:80"
  sysmetrics:
    port: 1024
    url: "http://sysmetrics:1024/metrics"
  grafana:
    port: 3000
    url: "http://grafana:3000"
  prometheus:
    port: 9090
    url: "http://prometheus:9090"
