events {}

http {
    include mime.types;
    server {
        server_name hauslab;
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /readings {
            proxy_pass http://gasmetrics-server:1024;
        }
    }
    server {
        server_name grafana.hauslab;
        listen 80;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://grafana:3000;
        }
    }
    server {
        server_name prometheus.hauslab;
        listen 80;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://prometheus:9090;
        }
    }
    server {
        server_name adguard.hauslab;
        listen 80;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://adguard:80;
        }
    }
    server {
        server_name setup.adguard.hauslab;
        listen 80;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://adguard:3000;
        }
    }
}
