name: postgres

services:
  postgres:
    image: postgres:17.9
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=s-gas
      - POSTGRES_DB=gasmetrics
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

secrets:
  postgres_password:
    file: secrets/postgres_password.txt
