name: observability

services:
  prometheus:
    image: prom/prometheus:v3.11.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - hauslab
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.4
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - hauslab
    secrets:
      - grafana_password
    environment:
      - GF_SECURITY_ADMIN_USER=s-gas
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}

secrets:
  grafana_password:
    file: secrets/grafana_password.txt

networks:
  hauslab:
    external: true
