global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "sysmetrics"
    static_configs:
      - targets: ["sysmetrics:1024"]
  - job_name: "svcmonitor"
    static_configs:
      - targets: ["svcmonitor:1025"]
