name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run tests for gasmetrics
        run: cd services/gasmetrics/gasmetrics && go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push svcmonitor
        uses: docker/build-push-action@v7
        with:
          context: services/svcmonitor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/svcmonitor:latest

      - name: Build and push sysmetrics
        uses: docker/build-push-action@v7
        with:
          context: services/sysmetrics
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sysmetrics:latest

      - name: Build and push gasmetrics
        uses: docker/build-push-action@v7
        with:
          context: services/gasmetrics/gasmetrics
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gasmetrics:latest
